<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'field.profile2.field_agama.profile_mahasiswa' => 'b9613c2929a6c32685293af6fe5a613d3c5c769f',
  'field.profile2.field_alamat.profile_mahasiswa' => 'f5515edb34d655095fc52036afada61e4845356b',
  'field.profile2.field_alamat_pokjar.profile_mahasiswa' => '2683a640a8a5e0a9901b507b59905881d0c0a01d',
  'field.profile2.field_jenis_kelamin.profile_mahasiswa' => 'a5f907bdfbe705e6ec6e9213e8f0b65e00e2a30a',
  'field.profile2.field_jurusan_asal.profile_mahasiswa' => 'baef33c30fb2438a308af147009c0527c4faaa03',
  'field.profile2.field_kewarganegaraan.profile_mahasiswa' => '6f8adaf409ef51fa3defa35eaa1abafd0e7b9c04',
  'field.profile2.field_kode_kabko_pokjar.profile_mahasiswa' => '76f60eb0214c03b99b3eb775585eb18708f5a67f',
  'field.profile2.field_kode_kabko_rumah.profile_mahasiswa' => '32557d8e10e7040bfaae8b9804ff495d9d4c7842',
  'field.profile2.field_kode_kabko_tpu.profile_mahasiswa' => 'a110d9c596762c8d57a28298c9406e16513b370b',
  'field.profile2.field_kode_pos_pokjar.profile_mahasiswa' => 'c4b41ff2ac018d23c834e78a93d4b9b8d3422dfe',
  'field.profile2.field_kode_pos_rumah.profile_mahasiswa' => 'a522f1e3a00531930d2491dbf8b0713cf5676303',
  'field.profile2.field_lama_mengajar.profile_mahasiswa' => '5979749d1f0f7c999fc403b80c796159b45d7569',
  'field.profile2.field_nama_mahasiswa.profile_mahasiswa' => 'f983d24dd64db3539d0dbcc5a0d5822564191518',
  'field.profile2.field_no_hp.profile_mahasiswa' => '2e73150ab49d30ebbec8279119f9fa9f590e884e',
  'field.profile2.field_pendidikan_akhir.profile_mahasiswa' => '74bff225c17e7a60d07efa9f71b08dbecbffab8c',
  'field.profile2.field_status_kawin.profile_mahasiswa' => 'e9bc88862dfaf185be7837b7a7886cf6ae4022f5',
  'field.profile2.field_tahun_ijazah.profile_mahasiswa' => '29937cbee17bcf63b04ca413fc1a53af3cc6f86b',
  'field.profile2.field_tanggal_lahir.profile_mahasiswa' => '1b535d4d1e8f62e9399fb06612f3708d679f2d63',
  'field.profile2.field_tempat_lahir.profile_mahasiswa' => '433c6875b64e726c0e8372b38a5b48e744bcecc1',
  'field.profile2.field_upbjj.profile_mahasiswa' => '63b56c9940a76e1dfabfa3a86041531dc6cde90d',
  'variable.field_bundle_settings_profile2__main' => '4ad00a966fedf217346991a2dc655f87a4ec6f13',
  'variable.field_bundle_settings_profile2__profile_mahasiswa' => '8e4df04ac26ff4f384a6d324ed7fadf3fd03405b',
  'profile2_type.main' => 'be0e7a4b8d7f5d4cbde8d35cbb0e2dbffc96d918',
  'profile2_type.profile_mahasiswa' => 'd084dceb4bb0f24c45af77c3cc2b284e3aad166f',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'field_sql_storage',
  'text',
  'entity',
  'profile2',
);
