<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'field.commerce_customer_profile.field_agama.billing' => '64621b9537877c285757eca0ca26e55d0287be31',
  'field.commerce_customer_profile.field_alamat.billing' => '3e90c3f237ec4edf3d218a74c87c232cee2f390d',
  'field.commerce_customer_profile.field_alamat_pokjar.billing' => 'b4afca016d71fc30b2b78cdd6a4884e31445e70c',
  'field.commerce_customer_profile.field_jenis_kelamin.billing' => 'ffcb51f892e42dee617c4d9e5988eb2916682dcb',
  'field.commerce_customer_profile.field_jurusan_asal.billing' => 'd57a82a5938925fe50bf7064442488cb1deeb079',
  'field.commerce_customer_profile.field_kabko_tpu.billing' => '3aa687330f67449f0597201713b58fcf83d8b240',
  'field.commerce_customer_profile.field_kewarganegaraan.billing' => 'e23920ac5cf37a8d54c36ef360f660761ebd6054',
  'field.commerce_customer_profile.field_kode_kabko_rumah.billing' => 'ffd9d3d1eef9cea4cce0c850228160ba0aed14db',
  'field.commerce_customer_profile.field_kode_pos_pokjar.billing' => 'f6492a27134ecf62f048597721f24ec953b05a91',
  'field.commerce_customer_profile.field_kode_pos_rumah.billing' => '3b665ebc1dcd4f8d0a16fd481cc101c60cbe762f',
  'field.commerce_customer_profile.field_lama_mengajar.billing' => '42df4c7c22af2781e4118f7ad342be6fb8eac505',
  'field.commerce_customer_profile.field_nama_mahasiswa.billing' => '76c06cc7203d1eab940f53edd57ac1b32b444c26',
  'field.commerce_customer_profile.field_no_hp.billing' => '8a83720be91e1260e7a4e4488c03afd56bc6aa70',
  'field.commerce_customer_profile.field_pendidikan_akhir.billing' => 'db370c4775b6b990e1c216982c45352c0a081755',
  'field.commerce_customer_profile.field_program_studi.billing' => 'c510158edbc58d7a5931e673f834e8043905a8d4',
  'field.commerce_customer_profile.field_status_kawin.billing' => '2b472a060ad61300728e209482a271aa153c7645',
  'field.commerce_customer_profile.field_tahun_ijazah.billing' => '99ba833d4b9e7e3779ff565f1cae8ee6e818a5bc',
  'field.commerce_customer_profile.field_tanggal_lahir.billing' => 'a5ea09ada6a5abbfd230f271a13b52f52f5d9e54',
  'field.commerce_customer_profile.field_tempat_lahir.billing' => 'c10fdade8da8203b300024154625869c73c6dc4f',
  'field.commerce_customer_profile.field_upbjj_sro.billing' => 'af9963d52236a20405f17420a72cec2148aa0969',
  'field.commerce_line_item.commerce_display_path.bundle' => '6d96370a0398c1b48383f1741b021548153f3c61',
  'field.commerce_line_item.commerce_display_path.product' => '0cfd446b6ad53478eb3128c82088af54b4670465',
  'field.commerce_line_item.commerce_parent_line_item.bundle' => '04e158b17c720e997489a46f271b1c67a866aeb8',
  'field.commerce_line_item.commerce_product.bundle' => '93d691556f046ea1deafe9157eeec576d70008c0',
  'field.commerce_line_item.commerce_product.product' => '3fcc1ea26f2270ee57652398ef9ba66b42f7947e',
  'field.commerce_line_item.commerce_total.bundle' => '0a3b3319cc47d33940c742d211f2e6c255cf79d6',
  'field.commerce_line_item.commerce_total.product' => 'c3cc7dc081ca89a030b21a86e4d1eff1431bc950',
  'field.commerce_line_item.commerce_unit_price.bundle' => '6837b1a0df8b95f392365c3b35de9da53211e7de',
  'field.commerce_line_item.commerce_unit_price.product' => '30b65b53aa5b4cab63dab7b25c4d86f0f3d95c0e',
  'field.commerce_order.commerce_customer_billing.commerce_order' => '647988d6d756af51265ed0d9417b13f201193d9b',
  'field.commerce_order.commerce_line_items.commerce_order' => '61f6df9e099aff3eab5fa8fd3f5fc7cfe55fc5f1',
  'variable.commerce_customer_profile_billing_field' => '65ad7c8a4d94c78748c1648e776bb324ef0f078b',
  'variable.field_bundle_settings_commerce_customer_profile__billing' => '77d7fe85eae7423b7b087c9c2073cb4cb645632e',
  'variable.field_bundle_settings_commerce_line_item__product' => '82ece22b64b29b7025d3da3acadd3ac2819ef06d',
  'permission.administer_line_items' => '3efba00de9e30a060c5d1ee61ea888cfb2f0a6a7',
  'permission.administer_line_item_types' => '53891a307cfb070cefa5c6011871738126d6f8bb',
  'permission.create_commerce_customer_profile_entities_of_bundle_billing' => 'e4e210b0cbbdd45d2fbe21f13d95ca8dc34c5a59',
  'permission.edit_any_commerce_customer_profile_entity_of_bundle_billing' => '3ea43db84e46c406f9e8d9385a5aa69111f2e3ec',
  'permission.edit_own_commerce_customer_profile_entities_of_bundle_billing' => '043f1ebb6ed1e9a17642adf64cce5b2220e5c254',
  'permission.view_any_commerce_customer_profile_entity_of_bundle_billing' => 'b553d4cea46dce9a7136ad70dc3aec5ac1201d2e',
  'permission.view_own_commerce_customer_profile_entities_of_bundle_billing' => 'e196c9ee6c580bcbc808d5b66cce13fa4b388c56',
  'views_view.commerce_line_item_table' => 'f99fb8acd87f9e4fa0d6726b95efa4730a3afb2c',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'field_sql_storage',
  'text',
  'commerce_line_item',
  'commerce_product_reference',
  'commerce_price',
  'commerce_customer',
  'views',
);
