<?php
/**
 * @file
 * variable.field_bundle_settings_commerce_customer_profile__billing.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'field_bundle_settings_commerce_customer_profile__billing',
  'content' => array(
    'view_modes' => array(),
    'extra_fields' => array(
      'form' => array(),
      'display' => array(),
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
