<?php
/**
 * @file
 * variable.field_bundle_settings_commerce_line_item__product.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'field_bundle_settings_commerce_line_item__product',
  'content' => array(
    'view_modes' => array(),
    'extra_fields' => array(
      'form' => array(
        'label' => array(
          'weight' => '-10',
        ),
        'quantity' => array(
          'weight' => '-5',
        ),
      ),
      'display' => array(),
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
