<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'field.taxonomy_term.field_masa.master_masa' => '490444363bb9653f28372fc2e935566af9eb4e10',
  'variable.field_bundle_settings_taxonomy_term__master_masa' => 'f491826958360785819fad5c43a4aa7bb282847a',
  'vocabulary.master_masa' => 'f2b8b21b2cfcf1786f09599ffbc9ab300f2ad68d',
  'field_validation_rule.length_m_masa' => 'af456b35316d9ce3b90d6e716d1436f50b291652',
  'field_validation_rule.primary_key_m_masa' => '227224e9ba4a2ee90f9819ec0d1b3c91f39ec474',
  'views_view.master_masa' => '0edbe205f818aae20a27583670a52cdcf71c2a17',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'field_sql_storage',
  'text',
  'ctools',
  'field_validation',
  'views',
  'taxonomy',
);
