<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'field.taxonomy_term.field_kode_jenis_do.master_jenis_do' => 'd1603e1bdba43b799376a2222ca3083751d9f19e',
  'field.taxonomy_term.field_kode_jenis_pesan.master_jenis_pesan' => 'cfe66242c293d3fcb56f66aa3f4b6417cc03ea2f',
  'field.taxonomy_term.field_kode_status_aktif.master_status_aktif' => '7575e11152c1c1c3b336b7e6c6cfe187ec26c6a9',
  'field.taxonomy_term.field_kode_status_lelang.master_status_lelang' => 'cf4e63c2602b49b9d0e07b7e960f671cf18d9815',
  'field.taxonomy_term.field_kode_status_proses.master_proses_status' => '0a24b6fb58bcb126e6c5155da034e67c9ca60f93',
  'field.taxonomy_term.field_masa.master_masa' => '490444363bb9653f28372fc2e935566af9eb4e10',
  'variable.field_bundle_settings_taxonomy_term__master_jenis_do' => '9ba76875754334e9b9ab7b6504c35ccca92cf53c',
  'variable.field_bundle_settings_taxonomy_term__master_jenis_pesan' => 'cee0b4e5b75fde69037ae4f975d082acc3e60659',
  'variable.field_bundle_settings_taxonomy_term__master_masa' => 'f491826958360785819fad5c43a4aa7bb282847a',
  'variable.field_bundle_settings_taxonomy_term__master_proses_status' => '9ffa66b1b3b31eb690bb0438b1bace0e2623e2f0',
  'variable.field_bundle_settings_taxonomy_term__master_status_aktif' => '11699e4d6c27ada7781d6f343b91c237f9e44289',
  'variable.field_bundle_settings_taxonomy_term__master_status_lelang' => '54673cce0e0c6ea0adce89484e2116825b18dd6d',
  'permission.administer_master_jenis_do_vocabulary_terms' => 'cbd2d5ae9bca531b45b9b812c3bb782561d7ed70',
  'permission.administer_master_jenis_pesan_vocabulary_terms' => 'e275f766800f8947fbc6b815a1d148ddf32a6c7e',
  'permission.administer_master_masa_vocabulary_terms' => '8b9db81bbceaa0a0108900667cc4148c5266bb29',
  'permission.administer_master_proses_status_vocabulary_terms' => 'ed78a3bf7deaf91245d87b77ce74e965273ebf44',
  'permission.administer_master_status_aktif_vocabulary_terms' => 'e3f83568daa4591028b8bc21d0aa2a145a85d6ac',
  'permission.administer_master_status_lelang_vocabulary_terms' => '976b8d30c6ca9bf839be59d1381f6254072f2b03',
  'vocabulary.master_jenis_do' => '145757b665a743124de0dafdd0433463a7531d2d',
  'vocabulary.master_jenis_pesan' => '1223419c0847de000d62a7ceadb580f3ea1856ee',
  'vocabulary.master_masa' => '21a32232fb99f4edf1e375394dd818b88f0fbc9b',
  'vocabulary.master_proses_status' => '75aba8366017352815ef87949b26791eef41a972',
  'vocabulary.master_status_aktif' => '421216c4c9591b88b92467b4a2f9e599fd8e7580',
  'vocabulary.master_status_lelang' => '725e947c247b77039e6502158d8c912859a70f96',
  'menu.navigation' => '31195bbd6ac1400ce5f6c1924535c1a817a053b7',
  'menu_link.56fe22bc699daf6ec0a35530a4b057c2c0a2d203' => 'b6aeb83071234f80b28b89545e218baabcb96166',
  'field_validation_rule.length_jenis_pesan' => '0ad125e3c1f06427f7af1d10fc6ca28cf576c75b',
  'field_validation_rule.length_kd_jenis_do' => '8f7caf6a07a02ea70c94ba124274df4e0c7aa7cd',
  'field_validation_rule.length_kode_proses_status' => '28cc3007b22cb3c6a80686e310ac6518dc7e1fa0',
  'field_validation_rule.length_kode_status_aktif' => '4a252836b80cd944033d42d33172ed85efa731ea',
  'field_validation_rule.length_m_masa' => 'af456b35316d9ce3b90d6e716d1436f50b291652',
  'field_validation_rule.length_status_lelang' => '3651d6507cfb452f3fe3e55e9e57d16496c3737d',
  'field_validation_rule.primary_key_kd_jenis_do' => '1d1e1fa496d27f549bcfd0796e70fc55a1555ec5',
  'field_validation_rule.primary_key_kode_status_aktif' => 'bf829530885867f052584f9b7cb9c91c2da1d85a',
  'field_validation_rule.primary_key_kode_status_proses' => 'aec00af6c90253ffb92f81ebf1556a766c4e2bc0',
  'field_validation_rule.primary_key_m_masa' => '227224e9ba4a2ee90f9819ec0d1b3c91f39ec474',
  'field_validation_rule.unique_data_jenis_pesan' => '65808dfc2e2ce87aacb2d75b84d1dcc72f2a01e2',
  'field_validation_rule.unique_data_status_lelang' => '51487cd9ff041157ab9e47e896db21e4bbdcee18',
  'views_view.master_jenis_do' => '9487577b0e72e3bfcf11971f27ff8affb78d53b7',
  'views_view.master_jenis_pesan' => '4864b9af4509abca4e442870720bdf4ae770af60',
  'views_view.master_masa' => '0edbe205f818aae20a27583670a52cdcf71c2a17',
  'views_view.master_status_aktif' => '140a3d215f43228394188f2c64d4ebe15488d688',
  'views_view.master_status_lelang' => '9c265c93f458b49b934177aa3e2843c689a32dc7',
  'views_view.master_status_proses' => 'f0aa44beb0ab6123b97b0bf7282aba9276b4a456',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'field_sql_storage',
  'number',
  'text',
  'ctools',
  'field_validation',
  'vppr',
  'views',
  'taxonomy',
);
