<?php
/**
 * @file
 * field_validation_rule.unix_agama.inc
 */

$api = '2.0.0';

$data = $rule = new ();
$rule->disabled = FALSE; /* Edit this to true to make a default rule disabled initially */
$rule->api_version = 2;
$rule->rulename = '';
$rule->name = '';
$rule->field_name = '';
$rule->col = 'value';
$rule->entity_type = '';
$rule->bundle = '';
$rule->validator = '';
$rule->settings = '';
$rule->error_message = '';


$dependencies = array();

$optional = array();

$modules = array();
