<?php
/**
 * @file
 * menu_link.781f615e0970e9df6bcdba48739e55aae70fbafb.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'lama-ajar',
  'link_title' => 'Lama Ajar',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'lama-ajar',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.navigation' => 'menu.navigation',
);

$optional = array();

$modules = array();
