<?php
/**
 * @file
 * menu_link.3e339cb2b2e940ddb231d22246d808a255d3f00c.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'http://simpeg.local.ut.ac.id',
  'link_title' => 'Simpeg',
  'menu_name' => 'menu-sso-menu',
  'weight' => '-47',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
  ),
  'router_path' => '',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_sso_menu' => 'menu.menu_sso_menu',
);

$optional = array();

$modules = array();
