<?php
/**
 * @file
 * menu_link.68d73c236655f3c1869e25c5792a837b4fe3d39c.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'master-sumber-data',
  'link_title' => 'Sumber Data',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
  ),
  'router_path' => 'master-sumber-data',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.navigation' => 'menu.navigation',
);

$optional = array();

$modules = array();
