<?php
/**
 * @file
 * menu_link.ac0445c90eae3c54477daa8ebdda7989d21e7dfe.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'http://srs.local.ut.ac.id',
  'link_title' => 'SRS',
  'menu_name' => 'menu-sso-menu',
  'weight' => '-48',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
  ),
  'router_path' => '',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_sso_menu' => 'menu.menu_sso_menu',
);

$optional = array();

$modules = array();
