<?php
/**
 * @file
 * menu_link.a19f315d7de31756b9b703f2fe5f9cf0aa20daf7.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'master-agama',
  'link_title' => 'Agama',
  'menu_name' => 'navigation',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'master-agama',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.navigation' => 'menu.navigation',
);

$optional = array();

$modules = array();
