<?php
/**
 * @file
 * menu_link.b1f3900b28e0c6ca76cf7216fc7de1c38860b499.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'http://distribusi.local.ut.ac.id',
  'link_title' => 'Distribusi',
  'menu_name' => 'menu-sso-menu',
  'weight' => '-49',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
  ),
  'router_path' => '',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_sso_menu' => 'menu.menu_sso_menu',
);

$optional = array();

$modules = array();
