<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'field.taxonomy_term.field_abbreviation.master_fakultas' => '9f3be57bd60c55b418682413e4fe864e72c1afb8',
  'field.taxonomy_term.field_integer_code.master_fakultas' => '7321d08f91865c4dfcd708191f56506b08fa07f6',
  'field.taxonomy_term.field_integer_code.master_guru' => '61b6d7d904815aa6131b292ac3d946bbc7f0a7db',
  'permission.access_overlay' => '8689a870a7abab2f7e90baa567490edd4a7ca948',
  'permission.administer_master_fakultas_vocabulary_terms' => '6726753922cc75aa4d0bc62d3782fe7561d4f2e4',
  'permission.administer_master_guru_vocabulary_terms' => 'f50b6f8add91ba5db733b870c19dfbe1504d3ec5',
  'permission.delete_terms_in_1' => '76cf5f8950f540aea2eaa1ec2bc44b9df848c05f',
  'permission.delete_terms_in_2' => '6a9f40384975e21d435853d3bb81b7efa55ba51e',
  'permission.edit_terms_in_1' => '347586ebbe9dd43360066c8832e3681e16c3d003',
  'permission.edit_terms_in_2' => '39fa8d82142f8901b9d2296ba19fddde1eecc4e8',
  'vocabulary.master_fakultas' => '716054bc9651c13815ac84421ef22fa536f482a5',
  'vocabulary.master_guru' => 'fbc639f47cf99bea521bb8eb90a738f627a458f4',
  'feeds_importer.master_fakultas' => '459c6f0ad7750dae0ca48fe26e9158e3ae519b0a',
  'feeds_importer.users' => '4d600944e817228c78bebe38f6db121937e418d1',
  'views_view.master_fakultas' => '10a28cacdf7e01ad131be84175ceb151dd5b19b1',
  'views_view.master_guru' => 'b764dc885043ef9494875c13a27d7d2589ad9453',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'ctools',
  'feeds',
  'field_sql_storage',
  'text',
  'number',
  'overlay',
  'vppr',
  'taxonomy',
  'views',
);
