<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'field.taxonomy_term.field_abbreviation.master_fakultas' => '9f3be57bd60c55b418682413e4fe864e72c1afb8',
  'field.taxonomy_term.field_integer_code.master_fakultas' => '7321d08f91865c4dfcd708191f56506b08fa07f6',
  'permission.access_overlay' => '8689a870a7abab2f7e90baa567490edd4a7ca948',
  'permission.administer_master_fakultas_vocabulary_terms' => '6726753922cc75aa4d0bc62d3782fe7561d4f2e4',
  'permission.delete_terms_in_1' => '76cf5f8950f540aea2eaa1ec2bc44b9df848c05f',
  'permission.edit_terms_in_1' => '347586ebbe9dd43360066c8832e3681e16c3d003',
  'vocabulary.master_fakultas' => '716054bc9651c13815ac84421ef22fa536f482a5',
  'views_view.master_fakultas' => '46fecd3014f980053b251c23795d85518133d482',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'field_sql_storage',
  'text',
  'number',
  'overlay',
  'vppr',
  'taxonomy',
  'views',
);
