<?php
/**
 * @file
 * variable.field_bundle_settings_taxonomy_term__master_biner.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'field_bundle_settings_taxonomy_term__master_biner',
  'content' => array(
    'view_modes' => array(),
    'extra_fields' => array(
      'form' => array(
        'name' => array(
          'weight' => '-3',
        ),
        'description' => array(
          'weight' => '0',
        ),
      ),
      'display' => array(),
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
