<?php

/**
 * @file
 */

/**
 * Implements hook_init().
 */
function puskom_login_init() {

  $path = current_path();
  $is_api = substr($path, 0, 3);
  if ($is_api == 'api') {
    // do nothing.
  }
  elseif (php_sapi_name() != 'cli') {
    if (user_is_anonymous() && $path != 'user/login') {
      drupal_goto('user/login');
    }
  }
}

/**
 * Implements hook_menu_alter.
 */
function puskom_login_menu_alter(&$items) {
  $items['user/login']['type'] = MENU_CALLBACK;
  $items['user/password']['type'] = MENU_CALLBACK;
}

/**
 * Implements hook_form_ID_alter.
 */
function puskom_login_form_user_login_alter(&$form, &$form_state) {
  drupal_set_title(t(''));
}
